from flask import Flask, render_template, request
import pdfplumber
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
import spacy

app = Flask(__name__, template_folder='template', static_folder='static')

# Load spaCy's English language model
nlp = spacy.load("en_core_web_sm")

@app.route('/')
def index():
    return render_template('index.html', results=None, resume_info=None)

@app.route('/process', methods=['POST'])
def process():
    job_description = ""

    # Get uploaded job description file
    uploaded_jd = request.files['jd']

    try:
        with pdfplumber.open(uploaded_jd) as pdf:
            pages = pdf.pages[0]
            job_description = pages.extract_text()
    except:
        pass

    def getResult(JD_txt, resume_txt):
        content = [JD_txt, resume_txt]

        cv = CountVectorizer()

        matrix = cv.fit_transform(content)

        similarity_matrix = cosine_similarity(matrix)

        match = similarity_matrix[0][1] * 100

        return match

    match_results = []
    resume_info = []  # List to store extracted resume information

    # Get uploaded resume files as a list
    uploaded_resumes = request.files.getlist('resumes[]')

    for uploaded_resume in uploaded_resumes:
        resume = ""
        try:
            with pdfplumber.open(uploaded_resume) as pdf:
                pages = pdf.pages[0]
                resume = pages.extract_text()
        except:
            pass

        if job_description and resume:
            match = getResult(job_description, resume)
            match = round(match, 2)
            match_results.append(f"Match Percentage for Resume {uploaded_resume.filename}: {match}%")

            # Extract information from the resume
            name = extract_name(resume)
            email = extract_email(resume)
            skills = extract_skills(resume)  # Extract skills using spaCy

            resume_info.append({"name": name, "email": email, "skills": skills})
        else:
            match_results.append(f"Could not process Resume {uploaded_resume.filename}")

    return render_template('index.html', results=match_results, resume_info=resume_info)

# Add custom functions for extracting resume information here
import re

def extract_name(resume_text):
    # Extract a full name consisting of capitalized words
    name_pattern = re.compile(r'\b[A-Z][A-Z\s]+\b')
    matches = name_pattern.findall(resume_text)

    if matches:
        # Join the matches to form the full name
        full_name = ' '.join(matches)
        return full_name

    # If no valid name is found, return None or an appropriate placeholder
    return None
# Example usage:

def extract_email(resume_text):
    # Implement logic to extract the email from the resume_text
    # Example: Search for email patterns using regular expressions
    email_pattern = r'\S+@\S+'
    email_match = re.search(email_pattern, resume_text)
    if email_match:
        return email_match.group()
    return ""

def extract_skills(resume_text):
    # Implement logic to extract skills from the resume_text using spaCy
    skills = []
    doc = nlp(resume_text)
    
    # Customize this part to match the way skills are mentioned in your resumes
    skill_keywords = skill_keywords = [
    "python",
    "java",
    "c++",
    "javascript",
    "sql",
    "html",
    "css",
    "php",
    "ruby",
    "react",
    "angular",
    "vue.js",
    "node.js",
    "express.js",
    "flask",
    "django",
    "spring",
    "laravel",
    "asp.net",
    "docker",
    "kubernetes",
    "git",
    "agile",
    "scrum",
    "machine learning",
    "deep learning",
    "natural language processing",
    "data analysis",
    "data visualization",
    "artificial intelligence",
    "big data",
    "cloud computing",
    "devops",
    "cybersecurity",
    "networking",
    "database management",
    "software development",
    "web development",
    "mobile app development",
    "UI/UX design",
    "project management",
    "communication",
    "teamwork",
    "problem-solving",
    "critical thinking",
    "leadership",
    "time management",
    "creativity",
    "presentation skills",
    "customer service",
    "sales",
    "marketing",
    "financial analysis",
    "accounting",
    "foreign languages (e.g., Spanish, French)",
    "certifications (e.g., PMP, AWS Certified)",
    "statistics",
    "research",
    "teaching",
    "mentoring",
    "public speaking",
    "data entry",
    "quality control",
    "supply chain management",
    "event planning",
    "content writing",
    "social media marketing",
    "video editing",
    "graphic design",
    "photography",
    "scheduling",
    "inventory management",
    "mechanical engineering",
    "electrical engineering",
    "civil engineering",
    "product design",
    "3D modeling",
    "robotics",
    "agriculture",
    "healthcare",
    "pharmaceuticals",
    "nursing",
    "fitness training",
    "culinary skills",
    "automotive repair",
    "construction",
    "plumbing",
    "welding",
    "woodworking",
    "gardening",
    "event coordination",
    "interior design",
    "fashion design",
    "creative writing",
    "journalism",
    "poetry",
    "music composition",
    "dance",
    "acting",
    "fine arts",
    "athletics",
    "cooking",
    "baking",
    "foreign cuisine",
    "customer support",
    "help desk",
    "troubleshooting",
    "user experience (UX) design",
    "user interface (UI) design",
    "human resources",
    "employee relations",
    "recruitment",
    "talent acquisition",
    "employee training",
    "public relations",
    "event management",
    "market research",
    "data entry",
    "administrative support",
    "office management",
    "bookkeeping",
    "financial planning",
    "tax preparation",
    "investment analysis",
    "portfolio management",
    "legal research",
    "contract negotiation",
    "real estate",
    "architecture",
    "urban planning",
    "environmental science",
    "sustainability",
    "geographic information systems (GIS)",
    "mapping",
    "geology",
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "mathematics",
    "statistics",
    "economics",
    "finance",
    "marketing",
    "sales",
    "customer service",
    "public speaking",
    "writing",
    "editing",
    "content management",
    "social media",
    "digital marketing",
    "email marketing",
    "search engine optimization (SEO)",
    "pay-per-click (PPC) advertising",
    "affiliate marketing",
    "e-commerce",
    "branding",
    "market analysis",
    "business development",
    "strategic planning",
    "supply chain management",
    "logistics",
    "inventory control",
    "quality assurance",
    "process improvement",
    "lean manufacturing",
    "six sigma",
    "project management",
    "agile methodology",
    "scrum",
    "leadership",
    "team management",
    "conflict resolution",
    "emotional intelligence",
    "interpersonal skills",
    "negotiation",
    "problem-solving",
    "decision-making",
    "critical thinking",
    "adaptability",
    "time management",
    "stress management",
    "public relations",
    "crisis management",
    "event planning",
    "budgeting",
    "financial analysis",
    "investment banking",
    "risk management",
    "insurance",
    "actuarial science",
    "legal research",
    "paralegal",
    "court reporting",
    "medical transcription",
    "medical coding",
    "pharmacy",
    "nursing",
    "physical therapy",
    "occupational therapy",
    "radiology",
    "phlebotomy",
    "medical assisting",
    "veterinary medicine",
    "dental hygiene",
    "nutrition",
    "culinary arts",
    "pastry arts",
    "baking",
    "cooking",
    "restaurant management",
    "hospitality",
    "hotel management",
    "tourism",
    "event management",
    "museum studies",
    "library science",
    "archival science",
    "cultural heritage",
    "art history",
    "musicology",
    "film studies",
    "theatre arts",
    "dance",
    "choreography",
    "broadcasting",
    "journalism",
    "public speaking",
    "media production",
    "film production",
    "screenwriting",
    "cinematography",
    "acting",
    "voice acting",
    "music composition",
    "audio production",
    "sound design",
    "game development",
    "animation",
    "graphic design",
    "illustration",
    "web design",
    "user interface (UI) design",
    "user experience (UX) design",
    "3D modeling",
    "virtual reality (VR) development",
    "augmented reality (AR) development",
    "motion graphics",
    "fine arts",
    "studio art",
    "sculpture",
    "printmaking",
    "painting",
    "drawing",
    "ceramics",
    "textile arts",
    "fiber arts",
    "metalworking",
    "jewelry design",
    "woodworking",
    "blacksmithing",
    "glassblowing",
    "pottery",
    "gardening",
    "landscape design",
    "horticulture",
    "agriculture",
    "permaculture",
    "environmental science",
    "climate science",
    "conservation",
    "forestry",
    "wildlife biology",
    "marine biology",
    "ecology",
    "oceanography",
    "geology",
    "earth science",
    "astronomy",
    "astrophysics",
    "physics",
    "chemistry",
    "biochemistry",
    "biology",
    "genetics",
    "microbiology",
    "neuroscience",
    "psychology",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "economics",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "international relations",
    "law",
    "criminology",
    "forensic science",
    "sociology",
    "social work",
    "psychology",
    "counseling",
    "therapy",
    "nursing",
    "healthcare administration",
    "medical billing",
    "medical coding",
    "pharmacy",
    "dental assisting",
    "veterinary technology",
    "radiologic technology",
    "sonography",
    "paramedicine",
    "dietetics",
    "nutrition",
    "fitness training",
    "physical therapy",
    "occupational therapy",
    "speech therapy",
    "audiology",
    "public health",
    "epidemiology",
    "health informatics",
    "healthcare management",
    "healthcare administration",
    "healthcare finance",
    "medical laboratory science",
    "phlebotomy",
    "blood bank technology",
    "cytotechnology",
    "histotechnology",
    "medical imaging",
    "magnetic resonance imaging (MRI)",
    "computed tomography (CT)",
    "ultrasound",
    "nuclear medicine technology",
    "radiation therapy",
    "respiratory therapy",
    "cardiovascular technology",
    "surgical technology",
    "sterile processing",
    "anesthesia technology",
    "ophthalmic technology",
    "dialysis technology",
    "medical equipment repair",
    "surgical instrument repair",
    "medical transcription",
    "medical billing",
    "medical coding",
    "health information management",
    "healthcare administration",
    "dental hygiene",
    "nutrition",
    "dietetics",
    "food science",
    "culinary arts",
    "baking and pastry arts",
    "cooking",
    "restaurant management",
    "hospitality",
    "hotel management",
    "tourism",
    "event management",
    "museum studies",
    "library science",
    "archival science",
    "cultural heritage",
    "art history",
    "musicology",
    "film studies",
    "theatre arts",
    "dance",
    "choreography",
    "broadcasting",
    "journalism",
    "public speaking",
    "media production",
    "film production",
    "screenwriting",
    "cinematography",
    "acting",
    "voice acting",
    "music composition",
    "audio production",
    "sound design",
    "game development",
    "animation",
    "graphic design",
    "illustration",
    "web design",
    "user interface (UI) design",
    "user experience (UX) design",
    "3D modeling",
    "virtual reality (VR) development",
    "augmented reality (AR) development",
    "motion graphics",
    "fine arts",
    "studio art",
    "sculpture",
    "printmaking",
    "painting",
    "drawing",
    "ceramics",
    "textile arts",
    "fiber arts",
    "metalworking",
    "jewelry design",
    "woodworking",
    "blacksmithing",
    "glassblowing",
    "pottery",
    "gardening",
    "landscape design",
    "horticulture",
    "agriculture",
    "permaculture",
    "environmental science",
    "climate science",
    "conservation",
    "forestry",
    "wildlife biology",
    "marine biology",
    "ecology",
    "oceanography",
    "geology",
    "earth science",
    "astronomy",
    "astrophysics",
    "physics",
    "chemistry",
    "biochemistry",
    "biology",
    "genetics",
    "microbiology",
    "neuroscience",
    "psychology",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "economics",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "international relations",
    "law",
    "criminology",
    "forensic science",
    "sociology",
    "social work",
    "psychology",
    "counseling",
    "therapy",
    "nursing",
    "healthcare administration",
    "medical billing",
    "medical coding",
    "pharmacy",
    "dental assisting",
    "veterinary technology",
    "radiologic technology",
    "sonography",
    "paramedicine",
    "dietetics",
    "nutrition",
    "fitness training",
    "physical therapy",
    "occupational therapy",
    "speech therapy",
    "audiology",
    "public health",
    "epidemiology",
    "health informatics",
    "healthcare management",
    "healthcare administration",
    "healthcare finance",
    "medical laboratory science",
    "phlebotomy",
    "blood bank technology",
    "cytotechnology",
    "histotechnology",
    "medical imaging",
    "magnetic resonance imaging (MRI)",
    "computed tomography (CT)",
    "ultrasound",
    "nuclear medicine technology",
    "radiation therapy",
    "respiratory therapy",
    "cardiovascular technology",
    "surgical technology",
    "sterile processing",
    "anesthesia technology",
    "ophthalmic technology",
    "dialysis technology",
    "medical equipment repair",
    "surgical instrument repair",
    "medical transcription",
    "medical billing",
    "medical coding",
    "health information management",
    "healthcare administration",
    "dental hygiene",
    "nutrition",
    "dietetics",
    "food science",
    "culinary arts",
    "baking and pastry arts",
    "cooking",
    "restaurant management",
    "hospitality",
    "hotel management",
    "tourism",
    "event management",
    "museum studies",
    "library science",
    "archival science",
    "cultural heritage",
    "art history",
    "musicology",
    "film studies",
    "theatre arts",
    "dance",
    "choreography",
    "broadcasting",
    "journalism",
    "public speaking",
    "media production",
    "film production",
    "screenwriting",
    "cinematography",
    "acting",
    "voice acting",
    "music composition",
    "audio production",
    "sound design",
    "game development",
    "animation",
    "graphic design",
    "illustration",
    "web design",
    "user interface (UI) design",
    "user experience (UX) design",
    "3D modeling",
    "virtual reality (VR) development",
    "augmented reality (AR) development",
    "motion graphics",
    "fine arts",
    "studio art",
    "sculpture",
    "printmaking",
    "painting",
    "drawing",
    "ceramics",
    "textile arts",
    "fiber arts",
    "metalworking",
    "jewelry design",
    "woodworking",
    "blacksmithing",
    "glassblowing",
    "pottery",
    "gardening",
    "landscape design",
    "horticulture",
    "agriculture",
    "permaculture",
    "environmental science",
    "climate science",
    "conservation",
    "forestry",
    "wildlife biology",
    "marine biology",
    "ecology",
    "oceanography",
    "geology",
    "earth science",
    "astronomy",
    "astrophysics",
    "physics",
    "chemistry",
    "biochemistry",
    "biology",
    "genetics",
    "microbiology",
    "neuroscience",
    "psychology",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "economics",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "international relations",
    "law",
    "criminology",
    "forensic science",
    "sociology",
    "social work",
    "psychology",
    "counseling",
    "therapy",
    "nursing",
    "healthcare administration",
    "medical billing",
    "medical coding",
    "pharmacy",
    "dental assisting",
    "veterinary technology",
    "radiologic technology",
    "sonography",
    "paramedicine",
    "dietetics",
    "nutrition",
    "fitness training",
    "physical therapy",
    "occupational therapy",
    "speech therapy",
    "audiology",
    "public health",
    "epidemiology",
    "health informatics",
    "healthcare management",
    "healthcare administration",
    "healthcare finance",
    "medical laboratory science",
    "phlebotomy",
    "blood bank technology",
    "cytotechnology",
    "histotechnology",
    "medical imaging",
    "magnetic resonance imaging (MRI)",
    "computed tomography (CT)",
    "ultrasound",
    "nuclear medicine technology",
    "radiation therapy",
    "respiratory therapy",
    "cardiovascular technology",
    "surgical technology",
    "sterile processing",
    "anesthesia technology",
    "ophthalmic technology",
    "dialysis technology",
    "medical equipment repair",
    "surgical instrument repair",
    "medical transcription",
    "medical billing",
    "medical coding",
    "health information management",
    "healthcare administration",
    "dental hygiene",
    "nutrition",
    "dietetics",
    "food science",
    "culinary arts",
    "baking and pastry arts",
    "cooking",
    "restaurant management",
    "hospitality",
    "hotel management",
    "tourism",
    "event management",
    "museum studies",
    "library science",
    "archival science",
    "cultural heritage",
    "art history",
    "musicology",
    "film studies",
    "theatre arts",
    "dance",
    "choreography",
    "broadcasting",
    "journalism",
    "public speaking",
    "media production",
    "film production",
    "screenwriting",
    "cinematography",
    "acting",
    "voice acting",
    "music composition",
    "audio production",
    "sound design",
    "game development",
    "animation",
    "graphic design",
    "illustration",
    "web design",
    "user interface (UI) design",
    "user experience (UX) design",
    "3D modeling",
    "virtual reality (VR) development",
    "augmented reality (AR) development",
    "motion graphics",
    "fine arts",
    "studio art",
    "sculpture",
    "printmaking",
    "painting",
    "drawing",
    "ceramics",
    "textile arts",
    "fiber arts",
    "metalworking",
    "jewelry design",
    "woodworking",
    "blacksmithing",
    "glassblowing",
    "pottery",
    "gardening",
    "landscape design",
    "horticulture",
    "agriculture",
    "permaculture",
    "environmental science",
    "climate science",
    "conservation",
    "forestry",
    "wildlife biology",
    "marine biology",
    "ecology",
    "oceanography",
    "geology",
    "earth science",
    "astronomy",
    "astrophysics",
    "physics",
    "chemistry",
    "biochemistry",
    "biology",
    "genetics",
    "microbiology",
    "neuroscience",
    "psychology",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "economics",
    "sociology",
    "anthropology",
    "archaeology",
    "linguistics",
    "philosophy",
    "history",
    "political science",
    "international relations",
    "law",
    "criminology",
    "forensic science",
    "sociology",
    "social work",
    "psychology",
    "counseling",
    "therapy",
    "nursing",
    "healthcare administration"
    ]

    
    for token in doc:
        if token.text.lower() in skill_keywords:
            skills.append(token.text)
    
    return skills

@app.route('/about')
def about():
    return render_template('about.html')

if __name__ == '__main__':
    app.run(debug=True)
